---
- name: Install Android SDKs for applicable releases
  command: "{{ android_sdk_install_location }}/sdk-install.expect"
  # Skip linting here, because I need to implement something more sane for checking pre-installed SDKs
  tags:
    - skip_ansible_lint

#- name: Add Android SDKs
##  shell: "(while sleep 3; do echo 'y'; done) | android update sdk --no-ui --silent --filter {{ item }}"
#  shell: "android update sdk --no-ui --filter {{ item }}"
#  args:
#     chdir: "{{ android_sdk_install_location }}"
#     executable: /bin/bash
#  with_items: "{{ android_sdk_tools_to_install }}"
